# Generated by Django 3.1.13 on 2022-01-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='作成者')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新者')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除日')),
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='タスクID')),
                ('task_service', models.CharField(max_length=16, verbose_name='タスクサービス名')),
                ('task_service_id', models.IntegerField(verbose_name='タスクサービスID')),
                ('task_name', models.CharField(max_length=64, verbose_name='タスク名')),
                ('task_category', models.IntegerField(choices=[(0, '単発実行'), (1, '予定実行')], verbose_name='タスクカテゴリー')),
                ('task_status', models.IntegerField(choices=[(0, '待機中'), (1, '実行中'), (2, '完了'), (3, 'エラー'), (9, 'テスト')], verbose_name='タスクステータス')),
                ('reserve_start', models.DateTimeField(blank=True, null=True, verbose_name='予約開始日時')),
                ('run_start', models.DateTimeField(blank=True, null=True, verbose_name='実行開始日時')),
                ('run_end', models.DateTimeField(blank=True, null=True, verbose_name='実行終了日時')),
                ('max_time', models.IntegerField(blank=True, null=True, verbose_name='実行最大時間（分）')),
                ('notification_emails', models.CharField(blank=True, max_length=256, null=True, verbose_name='通知メール先')),
                ('notification_slack_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='通知スラック先')),
                ('task_message', models.CharField(blank=True, max_length=256, null=True, verbose_name='タスクメッセージ')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
