# Generated by Django 3.1.13 on 2022-05-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_service_id',
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('create_user', models.CharField(default='admin', max_length=32, verbose_name='作成者')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='更新者')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除日')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='url')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='scheduler.task')),
            ],
            options={
                'db_table': 'task_option',
            },
        ),
    ]
